// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin"
type AppRouteHandlerRoutes = "/api/admin/bookings" | "/api/admin/cms/[entity]" | "/api/admin/cms/[entity]/[id]" | "/api/admin/cms/[entity]/[id]/publish" | "/api/admin/cms/retreats/[id]/itinerary" | "/api/admin/content" | "/api/admin/login" | "/api/admin/upload" | "/api/bookings" | "/api/public/blogs" | "/api/public/blogs/[slug]" | "/api/public/enquiries" | "/api/public/founder" | "/api/public/quotes" | "/api/public/retreats" | "/api/public/retreats/[slug]" | "/api/public/retreats/featured" | "/api/public/site-settings" | "/api/public/testimonials"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/admin/bookings": {}
  "/api/admin/cms/[entity]": { "entity": string; }
  "/api/admin/cms/[entity]/[id]": { "entity": string; "id": string; }
  "/api/admin/cms/[entity]/[id]/publish": { "entity": string; "id": string; }
  "/api/admin/cms/retreats/[id]/itinerary": { "id": string; }
  "/api/admin/content": {}
  "/api/admin/login": {}
  "/api/admin/upload": {}
  "/api/bookings": {}
  "/api/public/blogs": {}
  "/api/public/blogs/[slug]": { "slug": string; }
  "/api/public/enquiries": {}
  "/api/public/founder": {}
  "/api/public/quotes": {}
  "/api/public/retreats": {}
  "/api/public/retreats/[slug]": { "slug": string; }
  "/api/public/retreats/featured": {}
  "/api/public/site-settings": {}
  "/api/public/testimonials": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
