// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cms/[entity]/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cms/[entity]/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cms/[entity]/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cms/[entity]/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cms/[entity]/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cms/[entity]/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cms/[entity]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cms/[entity]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cms/[entity]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cms/retreats/[id]/itinerary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cms/retreats/[id]/itinerary">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cms/retreats/[id]/itinerary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/content">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/blogs/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/blogs/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/blogs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/blogs">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/blogs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/enquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/enquiries">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/enquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/founder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/founder">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/founder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/retreats/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/retreats/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/retreats/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/retreats/featured/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/retreats/featured">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/retreats/featured/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/retreats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/retreats">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/retreats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/site-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/site-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/site-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/testimonials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/testimonials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
